package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForm<M extends BaseForm<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setIsEnabled(java.lang.Boolean isEnabled) {
		set("isEnabled", isEnabled);
		return (M)this;
	}
	
	public java.lang.Boolean getIsEnabled() {
		return get("isEnabled");
	}

	public M setIsRelationModel(java.lang.Boolean isRelationModel) {
		set("isRelationModel", isRelationModel);
		return (M)this;
	}
	
	public java.lang.Boolean getIsRelationModel() {
		return get("isRelationModel");
	}

	public M setFormModelId(java.lang.Long formModelId) {
		set("formModelId", formModelId);
		return (M)this;
	}
	
	public java.lang.Long getFormModelId() {
		return getLong("formModelId");
	}

	public M setContentId(java.lang.Long contentId) {
		set("contentId", contentId);
		return (M)this;
	}
	
	public java.lang.Long getContentId() {
		return getLong("contentId");
	}

	public M setFormFieldValue(java.lang.String formFieldValue) {
		set("formFieldValue", formFieldValue);
		return (M)this;
	}
	
	public java.lang.String getFormFieldValue() {
		return getStr("formFieldValue");
	}

}
