package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCategory<M extends BaseCategory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setGrade(java.lang.Integer grade) {
		set("grade", grade);
		return (M)this;
	}
	
	public java.lang.Integer getGrade() {
		return getInt("grade");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}
	
	public java.lang.String getImage() {
		return getStr("image");
	}

	public M setIsMenu(java.lang.Boolean isMenu) {
		set("isMenu", isMenu);
		return (M)this;
	}
	
	public java.lang.Boolean getIsMenu() {
		return get("isMenu");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setTreePath(java.lang.String treePath) {
		set("treePath", treePath);
		return (M)this;
	}
	
	public java.lang.String getTreePath() {
		return getStr("treePath");
	}

	public M setParentId(java.lang.Long parentId) {
		set("parentId", parentId);
		return (M)this;
	}
	
	public java.lang.Long getParentId() {
		return getLong("parentId");
	}

	public M setContentModelId(java.lang.Long contentModelId) {
		set("contentModelId", contentModelId);
		return (M)this;
	}
	
	public java.lang.Long getContentModelId() {
		return getLong("contentModelId");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setListTemplate(java.lang.String listTemplate) {
		set("listTemplate", listTemplate);
		return (M)this;
	}
	
	public java.lang.String getListTemplate() {
		return getStr("listTemplate");
	}

	public M setListPageSize(java.lang.Integer listPageSize) {
		set("listPageSize", listPageSize);
		return (M)this;
	}
	
	public java.lang.Integer getListPageSize() {
		return getInt("listPageSize");
	}

	public M setContentTemplate(java.lang.String contentTemplate) {
		set("contentTemplate", contentTemplate);
		return (M)this;
	}
	
	public java.lang.String getContentTemplate() {
		return getStr("contentTemplate");
	}

	public M setPageTemplate(java.lang.String pageTemplate) {
		set("pageTemplate", pageTemplate);
		return (M)this;
	}
	
	public java.lang.String getPageTemplate() {
		return getStr("pageTemplate");
	}

	public M setPageContent(java.lang.String pageContent) {
		set("pageContent", pageContent);
		return (M)this;
	}
	
	public java.lang.String getPageContent() {
		return getStr("pageContent");
	}

	public M setLinkUrl(java.lang.String linkUrl) {
		set("linkUrl", linkUrl);
		return (M)this;
	}
	
	public java.lang.String getLinkUrl() {
		return getStr("linkUrl");
	}

	public M setIsEnabled(java.lang.Boolean isEnabled) {
		set("isEnabled", isEnabled);
		return (M)this;
	}
	
	public java.lang.Boolean getIsEnabled() {
		return get("isEnabled");
	}

	public M setDirectory(java.lang.String directory) {
		set("directory", directory);
		return (M)this;
	}
	
	public java.lang.String getDirectory() {
		return getStr("directory");
	}

}
