package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContentField<M extends BaseContentField<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setAlias(java.lang.String alias) {
		set("alias", alias);
		return (M)this;
	}
	
	public java.lang.String getAlias() {
		return getStr("alias");
	}

	public M setPrompt(java.lang.String prompt) {
		set("prompt", prompt);
		return (M)this;
	}
	
	public java.lang.String getPrompt() {
		return getStr("prompt");
	}

	public M setPattern(java.lang.String pattern) {
		set("pattern", pattern);
		return (M)this;
	}
	
	public java.lang.String getPattern() {
		return getStr("pattern");
	}

	public M setAttributeValue(java.lang.String attributeValue) {
		set("attributeValue", attributeValue);
		return (M)this;
	}
	
	public java.lang.String getAttributeValue() {
		return getStr("attributeValue");
	}

	public M setContentModelId(java.lang.Long contentModelId) {
		set("contentModelId", contentModelId);
		return (M)this;
	}
	
	public java.lang.Long getContentModelId() {
		return getLong("contentModelId");
	}

	public M setIsEnabled(java.lang.Boolean isEnabled) {
		set("isEnabled", isEnabled);
		return (M)this;
	}
	
	public java.lang.Boolean getIsEnabled() {
		return get("isEnabled");
	}

	public M setIsRequired(java.lang.Boolean isRequired) {
		set("isRequired", isRequired);
		return (M)this;
	}
	
	public java.lang.Boolean getIsRequired() {
		return get("isRequired");
	}

}
