package com.cms.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("kf_ad", "id", Ad.class);
		arp.addMapping("kf_ad_position", "id", AdPosition.class);
		arp.addMapping("kf_admin", "id", Admin.class);
		// Composite Primary Key order: adminId,roleId
		arp.addMapping("kf_admin_role", "adminId,roleId", AdminRole.class);
		arp.addMapping("kf_area", "id", Area.class);
		arp.addMapping("kf_category", "id", Category.class);
		arp.addMapping("kf_content", "id", Content.class);
		arp.addMapping("kf_content_field", "id", ContentField.class);
		arp.addMapping("kf_content_model", "id", ContentModel.class);
		arp.addMapping("kf_form", "id", Form.class);
		arp.addMapping("kf_form_field", "id", FormField.class);
		arp.addMapping("kf_form_model", "id", FormModel.class);
		arp.addMapping("kf_friend_link", "id", FriendLink.class);
		arp.addMapping("kf_role", "id", Role.class);
		arp.addMapping("kf_setting", "id", Setting.class);
		arp.addMapping("kf_storage_plugin", "id", StoragePlugin.class);
		arp.addMapping("kf_tag", "id", Tag.class);
	}
}

